name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
        architecture: x64
    - run: python -m pip install --upgrade pip
    - run: pip install poetry==1.*
    - run: poetry install
    - run: poetry run coverage run -m pytest
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
